# 配置 端口
server:
  port: 8763

# 配置中心配置
spring:
  application:
    name: service-config
  cloud:
    config:
      label: master # 配置仓库的分支
      server:
        git:
          uri: https://github.com/SniperHeadShot/config  # 配置git仓库的地址
          search-paths: springcloud  # 配置仓库路径,可以配置多个,用,分割
          username: # 访问git仓库的用户名
          password: # 访问git仓库的用户密码
    bus:
      enabled: true # 刷新时，关闭安全验证
      trace:
        enabled: true # 开启消息跟踪
  rabbitmq:
    host: 101.132.45.166
    port: 5672
    username: yushen
    password: 123123

# Eureka Client配置
eureka:
  instance:
    hostname: 101.132.45.166
    # Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 30
    # Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

# Actuator 健康检查
management:
  endpoint:
    health:
      show-details: always # /actuator/health 显示详情
  endpoints:
    web:
      exposure:
        include: ["bus-refresh","health","info"]