# 配置 端口
server:
  port: 8686

# Eureka 注册信息
eureka:
  instance:
    prefer-ip-address: true # 使用IP注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    username: yushen
    password: 123123

# 配置中心配置
spring:
  application:
    name: service-config
  profiles:
      active: dev
  cloud:
    config:
      label: master # 配置仓库的分支
      server:
        git:
          uri: https://github.com/SniperHeadShot/config  # 配置git仓库的地址
          search-paths: common  # 配置仓库路径,可以用,分割配置多个
          username: # 访问git仓库的用户名
          password: # 访问git仓库的用户密码
    bus:
      enabled: true # 刷新时，关闭安全验证
      trace:
        enabled: true # 开启消息跟踪
  rabbitmq:
    host: 101.132.45.166
    port: 5672
    username: yushen
    password: 123123