# Eureka Client配置
eureka:
  instance:
    hostname: 101.132.45.166
    # Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 30
    # Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: false # 表示是否将自己注册到Eureka Server
    fetchRegistry: false  # 表示是否从Eureka Server获取注册信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

# Actuator 健康检查
management:
  endpoint:
    health:
      show-details: always # /actuator/health 显示详情
  endpoints:
    web:
      exposure:
        include: ["bus-refresh","health","info"]