server:
  port: 8761

spring:
  application:
    name: eureka-server

# Eureka Server
eureka:
  instance:
    appname: 192.168.9.164
  client:
    fetch-registry: false # 此应用为注册中心，false：不向注册中心注册自己
    register-with-eureka: false # 注册中心职责是维护服务实例，false：不检索服务
    service-url:
      defaultZone: http://${eureka.instance.appname}:${server.port}/eureka/
  server:
    enable-self-preservation: false # 关闭自我保护机制
    eviction-interval-timer-in-ms: 3000 # 清理间隔，并且每次主动失效检测时间间隔为3s
