server:
  port: 8000

custom:
  clientUrl: http://192.168.9.27:9001

feign:
  hystrix:
    enabled: true # 开启Fallback，因为Fallback是通过Hystrix实现的,所以需要开启Hystrix

## 设置FeignClient日志等级
logging:
  level:
    com.bat.feign.clients: debug