server:
  port: 8761

# Eureka 服务注册中心配置
eureka:
  instance:
    hostname: 101.132.45.166
  client:
    registerWithEureka: false # 表示是否将自己注册到Eureka Server
    fetchRegistry: false  # 表示是否从Eureka Server获取注册信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  server:
    enable-self-preservation: false # 关闭保护机制
    eviction-interval-timer-in-ms: 60000  # 剔除失效服务间隔

# Actuator 健康检查
management:
  endpoint:
    health:
      show-details: always # /actuator/health 显示详情
  endpoints:
    web:
      exposure:
        include: ["health","info"]