server:
  port: 9001

spring:
  application:
    name: eureka-client

eureka:
  instance:
    hostname: 192.168.9.27
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 3 # 每隔时间间隔主动心跳一次，更新自己的状态
    lease-expiration-duration-in-seconds: 9 # 设置服务过期时间，过期则将这个实例剔除
  client:
    service-url:
      fetch-registry: true # 从Eureka Server拉取服务地址清单后缓存到本地
      registry-fetch-interval-seconds: 6 # 更新客户端缓存的服务清单时间间隔
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/