server:
  port: 9000

spring:
  application:
    name: eureka-client

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/