# Eureka 注册
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

# Actuator 健康检查
management:
  endpoint:
    health:
      show-details: always # /actuator/health 显示详情
  endpoints:
    web:
      exposure:
        include: ["*"]