# 配置 端口
#server:
#  port: 8900
spring:
  application:
    name: service-quartz
  profiles:
    active: dev

  # redis 配置
  redis:
    host: 101.132.45.166
    port: 6379
    password: zyagmx1314
    database: 15
    jedis:
      pool:
        max-active: 8
        max-idle: 500
        max-wait: -1ms



